//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStartup.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.TokenAssociates = new HashSet<TokenAssociate>();
        }

        [Key]
        public System.Guid UserId { get; set; }
        [EmailAddress]
        [Required]
        public string EmailAddress { get; set; }
        public byte[] EmailAddressHash { get; set; }
        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }
        public string Salt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }

        public string Error { get; set; }
        public virtual ICollection<TokenAssociate> TokenAssociates { get; set; }
    }
}
